name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v3

      - name: Build and Test Server
        run: |
          cd Backend
          echo "NPM cache directory: $(npm config get cache)"
          ls -al /home/runner/.npm
          npm cache clean -f
          rm -rf node_modules/
          npm update
          npm install
          npm start &
          # Add any server-specific build and test commands here

      - name: Build and Test Client
        run: |
          cd Frontend
          echo "NPM cache directory: $(npm config get cache)"
          ls -al /home/runner/.npm
          npm cache clean -f
          npm install
          npm rebuild node-sass  # Rebuild node-sass to fix potential build issues
          npm start &
          # Add any client-specific build and test commands here
